version: '3.8'

services:
  # PHP-FPM service
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: php-base
    container_name: afs-mappingxt-php-fpm
    restart: unless-stopped
    volumes:
      # Mount application code
      - .:/var/www/html
      # Mount logs
      - ./logs:/var/www/html/logs
      # Mount databases
      - ./db:/var/www/html/db
      # Mount media files
      - ./Files:/var/www/html/Files
      # PHP-FPM socket for Apache
      - php-fpm-socket:/run/php
    environment:
      # MSSQL Connection (override in .env)
      - AFS_MSSQL_HOST=${AFS_MSSQL_HOST:-10.0.1.82}
      - AFS_MSSQL_PORT=${AFS_MSSQL_PORT:-1435}
      - AFS_MSSQL_DB=${AFS_MSSQL_DB:-AFS_WAWI_DB}
      - AFS_MSSQL_USER=${AFS_MSSQL_USER:-sa}
      - AFS_MSSQL_PASS=${AFS_MSSQL_PASS:-W3laf!x}
      # PHP Configuration
      - PHP_MEMORY_LIMIT=256M
      - PHP_MAX_EXECUTION_TIME=300
      - TZ=Europe/Berlin
    networks:
      - afs-network
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  # Apache Web Server with mpm_event
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      target: apache
    container_name: afs-mappingxt-apache
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      # Mount application code (read-only for security)
      - .:/var/www/html:ro
      # Mount PHP-FPM socket
      - php-fpm-socket:/run/php
      # Mount Apache logs
      - ./logs/apache:/var/log/apache2
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - afs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    container_name: afs-mappingxt-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT:-8081}:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - afs-network
    profiles:
      - tools

volumes:
  # Shared socket volume for Apache <-> PHP-FPM communication
  php-fpm-socket:

networks:
  afs-network:
    driver: bridge
